### ISSUE TITLE
Неиспользуемое значение

### ISSUE THREAD

**Issue by AKitavtsev** [tri3h/webserver#47]
create :: Monad m => Handle m -> CreateUser -> Admin -> m (Either Error Token)
create handle partUser fAdmin = do
  fToken <- generateToken handle

Для чего нам это значение?

**Comment by tri3h** [comment]
Оно нужно при создании пользователя, я использую RecordWildCards чтобы занести его в FullUser в `..`
```
let user =
        FullUser
          { fName = cName partUser,
            fSurname = cSurname partUser,
            fAvatar = cAvatar partUser,
            fLogin = cLogin partUser,
            fPassword = hashPassw,
            ..
          }
```

**Comment by AKitavtsev** [comment]
Я понимаю, что это работает. Но я, например не имел дело с таким синтаксисом и думаю, что я не единственный. Согласись, что , если в user явно присвоить полю значение fToken будет значительно понятней

**Comment by AKitavtsev** [comment]
approved
